# generated by Buildyard, do not edit.

find_package(Lunchbox 1.5.0 REQUIRED)
if(Lunchbox_FOUND)
  set(Lunchbox_name Lunchbox)
elseif(LUNCHBOX_FOUND)
  set(Lunchbox_name LUNCHBOX)
endif()
if(Lunchbox_name)
  link_directories(${${Lunchbox_name}_LIBRARY_DIRS})
  include_directories(${${Lunchbox_name}_INCLUDE_DIRS})
endif()

find_package(Boost 1.41.0 REQUIRED serialization)
if(Boost_FOUND)
  set(Boost_name Boost)
elseif(BOOST_FOUND)
  set(Boost_name BOOST)
endif()
if(Boost_name)
  link_directories(${${Boost_name}_LIBRARY_DIRS})
  include_directories(${${Boost_name}_INCLUDE_DIRS})
endif()

